export const roleRows = [
  ['super_admin', 'Super Administrator', 'Full system access.'],
  ['system_admin', 'System Administrator', 'System-wide administration.'],
  ['station_manager', 'Station Manager', 'Station operations management.'],
  ['operator', 'Operator', 'Daily operational monitoring.'],
  ['auditor', 'Auditor', 'Read-only audit and report access.'],
];

export const permissionCodes = [
  'stations.read',
  'stations.create',
  'stations.update',
  'stations.deactivate',
  'devices.read',
  'devices.create',
  'devices.update',
  'devices.configure',
  'devices.restart',
  'devices.disable',
  'device_commands.read',
  'device_commands.create',
  'device_commands.cancel',
  'device_credentials.read',
  'device_credentials.create',
  'device_credentials.rotate',
  'device_credentials.revoke',
  'device_credentials.force_revoke',
  'device_events.read',
  'device_telemetry.read',
  'lockers.read',
  'lockers.configure',
  'lockers.emergency_open',
  'charging_ports.read',
  'charging_ports.configure',
  'payments.read',
  'charging_sessions.read',
  'alerts.read',
  'alerts.acknowledge',
  'alerts.resolve',
  'reports.read',
  'reports.export',
  'users.read',
  'users.create',
  'users.update',
  'roles.manage',
  'settings.read',
  'settings.update',
  'audit_logs.read',
];

export const rolePermissionMap = {
  system_admin: permissionCodes.filter((code) => code !== 'audit_logs.read'),
  station_manager: [
    'stations.read',
    'devices.read',
    'devices.update',
    'device_commands.read',
    'device_commands.create',
    'device_commands.cancel',
    'device_credentials.read',
    'device_credentials.create',
    'device_credentials.rotate',
    'device_credentials.revoke',
    'device_events.read',
    'device_telemetry.read',
    'lockers.read',
    'lockers.configure',
    'charging_ports.read',
    'charging_ports.configure',
    'charging_sessions.read',
    'payments.read',
    'alerts.read',
    'alerts.acknowledge',
    'alerts.resolve',
    'reports.read',
  ],
  operator: [
    'devices.read',
    'device_commands.read',
    'device_credentials.read',
    'device_events.read',
    'device_telemetry.read',
    'lockers.read',
    'charging_ports.read',
    'lockers.emergency_open',
    'charging_sessions.read',
    'payments.read',
    'alerts.read',
    'alerts.acknowledge',
  ],
  auditor: [
    'reports.read',
    'reports.export',
    'audit_logs.read',
    'device_events.read',
    'device_telemetry.read',
    'device_commands.read',
  ],
};
