export const roleRows = [
  ['super_admin', 'Super Administrator', 'Full system access.'],
  ['system_admin', 'System Administrator', 'System-wide administration.'],
  ['station_manager', 'Station Manager', 'Station operations management.'],
  ['operator', 'Operator', 'Daily operational monitoring.'],
  ['auditor', 'Auditor', 'Read-only audit and report access.'],
];

export const permissionCodes = [
  'stations.read',
  'stations.create',
  'stations.update',
  'stations.deactivate',
  'devices.read',
  'devices.create',
  'devices.update',
  'devices.configure',
  'devices.disable',
  'lockers.read',
  'lockers.configure',
  'lockers.emergency_open',
  'payments.read',
  'charging_sessions.read',
  'alerts.read',
  'alerts.acknowledge',
  'alerts.resolve',
  'reports.read',
  'reports.export',
  'users.read',
  'users.create',
  'users.update',
  'roles.manage',
  'settings.read',
  'settings.update',
  'audit_logs.read',
];

export const rolePermissionMap = {
  system_admin: permissionCodes.filter((code) => code !== 'audit_logs.read'),
  station_manager: [
    'stations.read',
    'devices.read',
    'devices.update',
    'lockers.read',
    'lockers.configure',
    'charging_sessions.read',
    'payments.read',
    'alerts.read',
    'alerts.acknowledge',
    'alerts.resolve',
    'reports.read',
  ],
  operator: [
    'devices.read',
    'lockers.read',
    'lockers.emergency_open',
    'charging_sessions.read',
    'payments.read',
    'alerts.read',
    'alerts.acknowledge',
  ],
  auditor: ['reports.read', 'reports.export', 'audit_logs.read'],
};
