export type DeviceResponse = {
  id: string;
  stationId: string;
  deviceCode: string;
  serialNumber: string;
  name: string;
  manufacturer: string | null;
  model: string | null;
  firmwareVersion: string | null;
  hardwareVersion: string | null;
  lifecycleStatus: string;
  connectivityStatus: string;
  operationalStatus: string;
  currentPowerSource: string;
  expectedHeartbeatIntervalSeconds: number;
  lastSeenAt: string | null;
  activatedAt: string | null;
  installedAt: string | null;
  maintenanceStartedAt: string | null;
  decommissionedAt: string | null;
  metadata: unknown;
  createdAt: string;
  updatedAt: string;
  createdByUserId: string | null;
  totalLockers?: number;
  availableLockers?: number;
  totalPorts?: number;
  activeSessions?: number;
};
